### ISSUE TITLE
go-cloud-debug-agent: not found error

### ISSUE THREAD

**Issue by acpower7** [googleapis/google-cloud-go#1378]
I am getting a an error trying to use go-cloud-debug-agent with cloud build.
cloudbuild.yaml
```

steps:
- name: 'gcr.io/cloud-builders/go'
  args: ["install", "-gcflags=-N", "-gcflags=-l", ".", ]
  env: ['PROJECT_ROOT=github.com/{repo-name}/{project-name}', 'CGO_ENABLED=0', 'GOOS=linux']
  
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/$IMG_NME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=8h

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - {deployment-name-yaml}
  - {container-name}=gcr.io/$PROJECT_ID/$IMG_NAME:$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE={zone-location}'
  - 'CLOUDSDK_CONTAINER_CLUSTER={cluster-name}'

```

Dockerfile:

```
FROM golang:alpine
# overkill
RUN apk update && apk add --virtual build-dependencies \
        build-base 
        gcc \
        wget \
        git \
    && apk add \
        bash

WORKDIR $GOPATH/src/github.com/{repo-name}/{project-name}
COPY . .

RUN go get -u cloud.google.com/go/cmd/go-cloud-debug-agent
RUN chmod +x /go/bin/go-cloud-debug-agent

CMD "/go/bin/go-cloud-debug-agent -sourcecontext=./source-context.json -appmodule=go-errrep -appversion=1.0 -- /go/bin/app-binary"

EXPOSE 80
``


I get error

```
{
 insertId:  "13ot4nzf67sw57"  
 labels: {…}  
 logName:  "projects/{project-instance-name}/logs/{container-name}"  
 receiveTimestamp:  "2019-03-30T04:21:23.985751935Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "/bin/sh: /go-cloud-debug-agent -sourcecontext=./source-context.json -appmodule=go-errrep -appversion=1.0 -- /go/bin/app-binary: not found
"  
 timestamp:  "2019-03-30T04:21:18.051998053Z"  
}
```


I've tried multiple variations as well, installing go-cloud-debug-agen via cloud build etc.

Would appreciate any answers on what i'm doing wrong.

thanks
