### ISSUE TITLE
Possible memory/goroutine leak in Dialogflow client

### ISSUE THREAD

**Issue by RoarkeRandall** [googleapis/google-cloud-go#1417]
## Client

e.g. Dialogflow v2 grpc client

## Describe Your Environment

e.g. Alpine docker in ECS

## Expected Behavior

Calling `sessionClient.Close()` will close all goroutines and GC will collect all memory. 

## Actual Behavior

Goroutines and memory are leftover after calling `sessionClient.Close()`

Since discovering this behavior, we have started using the sessionClient as a singleton so we no longer have a problem. While it may be less efficient, but we believe that creating a new client and closing more often should be a valid use case. 

I've attached png's of the heap and goroutine pprof dumps after about a day of usage where we create and close a sessionClient per request. 

[pprof.zip](https://github.com/googleapis/google-cloud-go/files/3143467/pprof.zip)

**Comment by jadekler** [comment]
cc @noahdietz since this is auto-generated

**Comment by noahdietz** [comment]
@jadekler The generated Close() method just wraps c.conn.Close(), where c.conn is a ClientConn produced by google.golang.org/api/transport

So I’m not sure that the bug would be in the generated code, unless it’s supposed to be doing more than calling ClientConn.Close().

**Comment by jadekler** [comment]
Gotcha. I don't see where the memory leak could be then... @RoarkeRandall which version of grpc are you using?

**Comment by RoarkeRandall** [comment]
@jadekler I don't know the grpc version. We pretty much used this guide/code verbatim: https://cloud.google.com/dialogflow-enterprise/docs/quickstart-api

Our glide lock file has the hash of the client code (cloud.google.com/go/dialogflow/apiv2), would that tell you the grpc version?

**Comment by RoarkeRandall** [comment]
Below is the git hash of the grpc package we are using. 
```
- name: google.golang.org/api
  version: d12b2951d36e6627abfad81531c463e34b685785
  subpackages:
  - googleapi/transport
  - internal
  - iterator
  - option
  - transport
  - transport/grpc
  - transport/http
  - transport/http/internal/propagation
```
