### ISSUE TITLE
bigtable: Service crashes because of 'Could not construct ApplicationDefaultCredentials'

### ISSUE THREAD

**Issue by AmardeepJassal** [googleapis/google-cloud-go#4370]
Hi Cloud Bigtable Team,

product : Bigtable

One of my customer is facing an issue with the emulator with docker compose.

He can see that the emulator is identified. Below is the client options dump

```
$clientOptions = {array} [15]
 serviceName = "google.bigtable.admin.v2.BigtableTableAdmin"
 apiEndpoint = "0.0.0.0:8087"
 clientConfig = "/var/www/vendor/google/cloud-bigtable/src/Admin/V2/Gapic/../resources/bigtable_table_admin_client_config.json"
 descriptorsConfigPath = "/var/www/vendor/google/cloud-bigtable/src/Admin/V2/Gapic/../resources/bigtable_table_admin_descriptor_config.php"
 gcpApiConfigPath = "/var/www/vendor/google/cloud-bigtable/src/Admin/V2/Gapic/../resources/bigtable_table_admin_grpc_config.json"
 credentialsConfig = {array} [2]
 transportConfig = {array} [3]
 disableRetries = false
 credentials = null
 transport = null
 gapicVersion = "1.10.1"
 libName = null
 libVersion = null
 hasEmulator = true
 emulatorHost = "0.0.0.0:8087"
```

Whenever the service starts it crashes because of  Could not construct ApplicationDefaultCredentials

Any idea on why the library tries to fetch the credentials, if he is trying to connect to the emulator and not to the cloud environment? He has already set the BIGTABLE_EMULATOR_HOST environment variable correctly.

He is starting the client from within docker-compose using this command cloud beta emulators bigtable start --host-port=0.0.0.0:8087

Also, adding the snippet from the compose yaml below:

```yaml
fast-transactions:
    image: eu.gcr.io/****-ops/base/php:7.3-xdebug
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - bigtable
    volumes:
      - ./:/var/www/
    command: ./bin/start-ledger-service.sh
    env_file:
      - ./platforms/docker/development.env
    environment:
      BIGTABLE_EMULATOR_HOST: '0.0.0.0:8087'
      SERVICE_NAME: 'fast-transactions'
    networks:
      - ledger-network
  bigtable:
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8087
    image: google/cloud-sdk:latest
    volumes:
      - ./:/var/www/
    environment:
      BIGTABLE_EMULATOR_HOST: '0.0.0.0:8087'
    ports:
      - 8087:8087
```

Any help in this regard will be highly appreciated to solve the issue
