### ISSUE TITLE
pubsub: 500 Error waiting for messages

### ISSUE THREAD

**Issue by onetwopunch** [googleapis/google-cloud-go#5133]
**Client**

PubSub

**Environment**
`golang:1.17-buster`

**Code**
```go
package listener
...
func (l *Listener) Run() {
	c, _ := json.Marshal(l.config)
	l.lg.Infof("Starting listener with config: %s", c)
	for {
		if err := l.sub.Receive(context.Background(), l.handleMessage); err != nil {
			l.lg.Errorf("Error receiving message: %s", err)
		}
	}
}
```

**Expected behavior**

`Receive()` should not throw a 500 error

**Actual behavior**

Messages are received and handled correctly when they come in, but if there's a long pause between messages, the `l.lg.Error` line is hit with the following 500 error:

```
MyApp: 2021/11/15 12:08:15 [ERROR] Error receiving message: 
  rpc error: 
    code = Unauthenticated desc = transport: compute: 
        Received 500 `Failed to generate federated token using STS:  context deadline exceeded`
```

I don't understand how it can actually be an authentication issue since it's able to pick up messages correctly when they arrive.

UPDATE:

Also the first message that comes in after a long pause between messages is not handled and errors out, but if you re-trigger that message, it works just fine.

**Additional Context**
This pod is using Workload Identities, which I've set up using the following terraform:

```hcl
resource "google_service_account_iam_member" "workload_identity" {
  for_each = toset([
    "roles/iam.workloadIdentityUser",
    "roles/iam.serviceAccountTokenCreator"
  ])
  service_account_id = google_service_account.myapp.name
  role               = each.key
  member             = "serviceAccount:${var.security_project}.svc.id.goog[myapp/worker]"
}
```

And k8s yaml:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: myapp
  annotations:
    iam.gke.io/gcp-service-account: "myapp@my-project.iam.gserviceaccount.com"

```

**Comment by onetwopunch** [comment]
Any insights on this?

**Comment by hongalex** [comment]
Hey, yeah this seems related to another workload identity issue that I saw before. I'll try to get a repro and see where the error is coming from.

**Comment by onetwopunch** [comment]
I _think_ I got this working (at least haven't seen the error for a while) with:

```yml
 initContainers:
  - image:  gcr.io/google.com/cloudsdktool/cloud-sdk:326.0.0-alpine
    name: workload-identity-initcontainer
    command:
    - '/bin/bash'
    - '-c'
    - |
      curl -s -H 'Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token' --retry 30 --retry-connrefused --retry-max-time 30 > /dev/null || exit 1
```

This is from: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#troubleshoot-timeout

In my deployment before my application. My theory is that when the first connection is made and fails because the metadata server isn't reachable, it maintains some cached non-token or something that it continues to try to use in a goroutine even after it's able to successfully auth later. That's the only way I can think of that would allow new connections to pass through, but still receive an error like this. Again, this is just a theory, but hopefully the link and initContainer help someone else. I'll leave this open since it should not be giving such a confusing error even if this is a known limitation of workload identity.
