### ISSUE TITLE
Dangerous workflow

### ISSUE THREAD

**Issue by gabibguti** [googleapis/google-cloud-go#9004]
**Code**

https://github.com/googleapis/google-cloud-go/blob/ca2493f43c299bbaed5f7e5b70f66cc763ff9802/.github/workflows/apidiff.yml#L83

**Actual behavior**

By referencing `${{ github.event.pull_request.head.ref }}` in a `run` executable block in `apidiff.yml` workflow, this workflow is subject to [script injection attacks](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack).

**Remediation**

One possible remediation is to [encapsulate this variable in a environment variable](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable).
```yml
    - name: Compare regenerated code to baseline
      # Only ignore Go interface additions when the PR is from OwlBot as it is
      # likely a new method added to the gRPC client stub interface, which is
      # non-breaking.
      env:
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      run: |
        cd ${{ matrix.changed }} && apidiff -m -incompatible ${{ steps.baseline.outputs.pkg }} . > diff.txt
        if [[ "$PR_HEAD_REF" == owl-bot-copy ]]; then
          sed -i '/: added/d' ./diff.txt
        fi
        cat diff.txt && ! [ -s diff.txt ]
```

**Additional context**

I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes.
