### ISSUE TITLE
storage: Cli unable to obtain ServiceAccount in K8s Cluster

### ISSUE THREAD

**Issue by CAJan93** [googleapis/google-cloud-go#9042]
# Error

The pod which throws below error mounts a ServiceAccount, but the error shows that the storage cli is falling back to the default ServiceAccount. I don't know why

```
Error was cannot list objects in bucket the-bucket-name.
Error was googleapi: Error 403: default-service-account@rwcdev.iam.gserviceaccount.com
does not have storage.objects.list access to the Google Cloud Storage bucket.
Permission 'storage.objects.list' denied on resource (or it may not exist)., forbidden
```

- `the-bucket-name` does exist. The issue is that the application does not use the service account 
- Either this is a GCP IAM issue (which I don't think) or this is an issue with the storage package not being able to pick-up the ServiceAccount

## Code 

```
// code from the-app, creating the GCP storage cli
ctx := context.Background()
scopes := []string{"https://www.googleapis.com/auth/cloud-platform"}
sdkCreds, err := google.FindDefaultCredentials(ctx, scopes...)
// handle err
client, err := storage.NewClient(ctx, opts.WithCredentials(sdkCreds))
// handle err
```

I attached a debugger and `FindDefaultCredentialsWithParams` calls below code in `/go/pkg/mod/golang.org/x/oauth2@v0.13.0/google/default.go`

```
// Fourth, if we're on Google Compute Engine, an App Engine standard second generation runtime,
// or App Engine flexible, use the metadata server.
if metadata.OnGCE() { 
	id, _ := metadata.ProjectID()
	return &Credentials{
		ProjectID:   id,
		TokenSource: computeTokenSource("", params.EarlyTokenRefresh, params.Scopes...),
	}, nil
}
``` 

As the snippet suggests there are other ways to find credentials. The service account mounts a token under `/var/path/to/file`. I tried setting `GOOGLE_APPLICATION_CREDENTIALS` to the relevant path, but this does not work, because its a account token and no credentials, I guess

## More Debugging notes: 

- The app is using a ServiceAccount and this Account has the relevant annotation (`kubectl` alias `k`)

```
k get ds the-app -o json | jq .spec.template.spec.serviceAccountName
"the-account"

k get serviceaccount the-app-service-account -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      iam.gke.io/gcp-service-account: the-app-service-account@rwcdev.iam.gserviceaccount.com
```

- They are both in the same ns. The AccountName is correct 
- `the-app-service-account@rwcdev.iam.gserviceaccount.com` does exist and has the relevant permissions 
- Using Terraform, I also created the relevant other objects in GCP IAM: `google_service_account_iam_member`, `google_project_iam_member`, and `google_service_account`

## Environment 

- GCP K8s cluster, container running inside a Pod 
- I deploy the app via helm not from calling it directly from my laptop and not the CI/CD pipeline

## Other 

I changed above outputs a little and hid things like role-names
