### ISSUE TITLE
logging: detectKubernetesResource() should set region not zone for location

### ISSUE THREAD

**Issue by tamayika** [googleapis/google-cloud-go#9070]
**Client**

Logging

**Environment**

on GKE

**Go Environment**

N/A

**Code**

N/A

**Expected behavior**

detectKubernetesResource() set region for location

**Actual behavior**

detectKubernetesResource() set zone for location

**Screenshots**

N/A

**Additional context**

`detectKubernetesResource()` currenly set zone(like "us-central1-b") for `location`.
But default stackdriver exporter in GKE uses region(like "us-central1") for `location` and GCP UI generates Cloud Logging URL which uses region for `location` at Pod logs page.
So, when developers want to switch from stackdriver exporter to direct exporter by this library, location value is not compatible between changes and default detection is not useful.

**Comment by minherz** [comment]
@tamayika can you please clarify what do you call "default stackdriver exporter" and to share an example of the resource metadata from the logs that are ingested by the default stackdriver exporter?

thank you

**Comment by tamayika** [comment]
This is the example of metadata which default stackdriver exporter uploads.(i.e. stdout or stderr logs metadata)

```yaml
resource:
  labels:
    cluster_name: "my-cluster"
    container_name: "my-container"
    location: "us-central1"
    namespace_name: "my-namespace"
    pod_name: "my-pod"
    project_id: "my-project"
  type: "k8s_container"
```

This is the example of metadata which current logging library uploads.
```yaml
resource:
  labels:
    cluster_name: "my-cluster"
    container_name: "my-container"
    location: "us-central1-b"
    namespace_name: "my-namespace"
    pod_name: "my-pod"
    project_id: "my-project"
  type: "k8s_container"
```

So, only `location` is different.
